version: '3.8'

services:
  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ukpostcode-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/dhl_hafizin_db
      SPRING_DATASOURCE_USERNAME: USERNAME
      SPRING_DATASOURCE_PASSWORD: PASSWORD
      GOOGLE_CLIENT_ID: CLIENT_ID
      GOOGLE_CLIENT_SECRET: CLIENT_SECRET
    ports:
      - "8080:8080"
